In [1]:
import pandas as pd

df = pd.read_csv('106_1_2_5.csv')

df.head()

,設立別,學校所在地別,畢業生人數,公立大學日間部人數,公立大學進修學士班人數,私立大學日間部人數,私立大學進修學士班人數,公立二專日間部人數,公立二專進修(夜間)部人數,私立二專日間部人數,...,私立大學進修學士班比率,公立二專日間部比率,公立二專進修(夜間)部比率,私立二專日間部比率,私立二專進修(夜間)部比率,警察大學比率,警察專科學校比率,軍事院校比率,赴國外_大陸就讀比率,其他學校比率
0,國立,新北市,482,95,4,326,8,0,0,0,...,1.66,0.00,0.00,0.00,0.00,0.00,0.41,0.00,5.19,0.00
1,國立,臺北市,1351,920,0,269,0,0,0,0,...,0.00,0.00,0.00,0.00,0.00,0.15,0.15,0.30,5.63,0.00
2,國立,桃園市,1589,734,28,612,24,10,2,1,...,1.51,0.63,0.13,0.06,0.31,0.06,0.06,1.13,0.50,0.88
3,國立,臺中市,1465,694,22,471,25,1,0,0,...,1.71,0.07,0.00,0.00,0.00,0.00,0.48,1.16,0.75,0.00
4,國立,臺南市,9999,3425,125,4315,439,33,0,1,...,4.39,0.33,0.00,0.01,0.00,0.00,0.58,1.12,0.46,0.01

In [2]:
temp = df[['學校所在地別', '畢業生人數', '公立大學日間部人數']]
temp

   學校所在地別  畢業生人數  公立大學日間部人數
0     新北市    482         95
1     臺北市   1351        920
2     桃園市   1589        734
3     臺中市   1465        694
4     臺南市   9999       3425
..    ...    ...        ...
61    基隆市   1796        360
62    新竹市   2808        241
63    嘉義市   2754        280
64    金門縣      0          0
65    連江縣      0          0

[66 rows x 3 columns]

In [13]:
Type = temp.groupby(['學校所在地別'])['公立大學日間部人數'].sum().reset_index()
Type['year'] = 106
Type

   學校所在地別  公立大學日間部人數  year
0     南投縣        808   106
1     嘉義市       1704   106
2     嘉義縣        451   106
3     基隆市        742   106
4     宜蘭縣        856   106
5     屏東縣       1304   106
6     彰化縣       3263   106
7     新北市       4455   106
8     新竹市       2169   106
9     新竹縣       1046   106
10    桃園市       5591   106
11    澎湖縣        293   106
12    臺中市       8547   106
13    臺北市      11077   106
14    臺南市       5069   106
15    臺東縣        339   106
16    花蓮縣        636   106
17    苗栗縣        777   106
18    連江縣         45   106
19    金門縣        163   106
20    雲林縣       1444   106
21    高雄市       7434   106

In [14]:
df107 = pd.read_csv('107_1_2_5.csv')
df108 = pd.read_csv('108_1_2_5.csv')
df109 = pd.read_csv('109_1_2_5.csv')

In [16]:
new = df107[['學校所在地別', '公立大學日間部人數']].groupby(['學校所在地別'])['公立大學日間部人數'].sum().reset_index()

In [17]:
new['year'] = 107
new

   學校所在地別  公立大學日間部人數  year
0     南投縣        757   107
1     嘉義市       1715   107
2     嘉義縣        387   107
3     基隆市        670   107
4     宜蘭縣        811   107
5     屏東縣       1150   107
6     彰化縣       3408   107
7     新北市       4053   107
8     新竹市       2332   107
9     新竹縣       1020   107
10    桃園市       5642   107
11    澎湖縣        294   107
12    臺中市       8766   107
13    臺北市      10678   107
14    臺南市       5172   107
15    臺東縣        302   107
16    花蓮縣        590   107
17    苗栗縣        832   107
18    連江縣         20   107
19    金門縣        193   107
20    雲林縣       1346   107
21    高雄市       6972   107

In [18]:
frames = [Type, new]

result = pd.concat(frames)

result

   學校所在地別  公立大學日間部人數  year
0     南投縣        808   106
1     嘉義市       1704   106
2     嘉義縣        451   106
3     基隆市        742   106
4     宜蘭縣        856   106
5     屏東縣       1304   106
6     彰化縣       3263   106
7     新北市       4455   106
8     新竹市       2169   106
9     新竹縣       1046   106
10    桃園市       5591   106
11    澎湖縣        293   106
12    臺中市       8547   106
13    臺北市      11077   106
14    臺南市       5069   106
15    臺東縣        339   106
16    花蓮縣        636   106
17    苗栗縣        777   106
18    連江縣         45   106
19    金門縣        163   106
20    雲林縣       1444   106
21    高雄市       7434   106
0     南投縣        757   107
1     嘉義市       1715   107
2     嘉義縣        387   107
3     基隆市        670   107
4     宜蘭縣        811   107
5     屏東縣       1150   107
6     彰化縣       3408   107
7     新北市       4053   107
8     新竹市       2332   107
9     新竹縣       1020   107
10    桃園市       5642   107
11    澎湖縣        294   107
12    臺中市       8766   107
13    臺北市      10678   107
14    臺南市       5172   107
15    臺東縣        302   107
16    花蓮縣        590   107
17    苗栗縣        832   107
18    連江縣         20   107
19    金門縣        193   107
20    雲林縣       1346   107
21    高雄市       6972   107

In [20]:
new1 = df108[['學校所在地別', '公立大學日間部人數']].groupby(['學校所在地別'])['公立大學日間部人數'].sum().reset_index()

new1['year'] = 108

new1

   學校所在地別  公立大學日間部人數  year
0     南投縣        770   108
1     嘉義市       1631   108
2     嘉義縣        388   108
3     基隆市        647   108
4     宜蘭縣        797   108
5     屏東縣       1124   108
6     彰化縣       3465   108
7     新北市       3854   108
8     新竹市       2398   108
9     新竹縣       1135   108
10    桃園市       5318   108
11    澎湖縣        287   108
12    臺中市       8669   108
13    臺北市      10543   108
14    臺南市       4954   108
15    臺東縣        416   108
16    花蓮縣        597   108
17    苗栗縣        887   108
18    連江縣         30   108
19    金門縣        150   108
20    雲林縣       1346   108
21    高雄市       6869   108

In [21]:
new2 = df109[['學校所在地別', '公立大學日間部人數']].groupby(['學校所在地別'])['公立大學日間部人數'].sum().reset_index()

new2['year'] = 109

new2

   學校所在地別  公立大學日間部人數  year
0     南投縣        751   109
1     嘉義市       1682   109
2     嘉義縣        414   109
3     基隆市        592   109
4     宜蘭縣        921   109
5     屏東縣       1191   109
6     彰化縣       3488   109
7     新北市       3842   109
8     新竹市       2483   109
9     新竹縣       1075   109
10    桃園市       5572   109
11    澎湖縣        259   109
12    臺中市       8650   109
13    臺北市      10878   109
14    臺南市       5053   109
15    臺東縣        412   109
16    花蓮縣        564   109
17    苗栗縣        851   109
18    連江縣         38   109
19    金門縣        196   109
20    雲林縣       1575   109
21    高雄市       7002   109

In [25]:
frames1 = [Type, new, new1, new2]

result = pd.concat(frames1)

result

   學校所在地別  公立大學日間部人數  year
0     南投縣        808   106
1     嘉義市       1704   106
2     嘉義縣        451   106
3     基隆市        742   106
4     宜蘭縣        856   106
..    ...        ...   ...
17    苗栗縣        851   109
18    連江縣         38   109
19    金門縣        196   109
20    雲林縣       1575   109
21    高雄市       7002   109

[88 rows x 3 columns]